title:              SDE Skills
email:              website@sdeskills.com
description:        Get upgraded of get deprecated!
author:             Vivek K
baseurl:            ""
url:                "https://www.sdeskills.com"

# Social Profiles
twitter_username:   sdeskills
github_username:    sde-skills
facebook_username:  sdeskills
linkedin_username:  sdeskills

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-20719240-1 # out your google-analytics code
facebook_pixel: 320571781954152
google_tagmanager: GTM-M7CTGG8

# Build settings
future: false
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
  - jekyll-redirect-from

collections:
  chapters:
    output: true
    permalink: /chapters/:path
  videos:
    output: true
    permalink: /youtube-channel/:path
